paths: 
  tabular_ehr_path: ../EHR_extract/outputs/tables/SP_table_EHR_pts.yaml.csv
  # test_ids_path: ../../data/img_data_link/ptb_population/test_EHR_population.json
  # train_ids_path: ../../data/img_data_link/ptb_population/train_EHR_population.json
  predictions_path: outputs/predictions/predictions_xgboost_SP_population.csv
  discards_path: outputs/predictions/discards_xgboost_SP_population.json

model:
  name: xgboost
  params:
    n_estimators: 500
    max_depth: 4
    learning_rate: 0.05
    subsample: 0.9
    colsample_bytree: 0.9
    reg_lambda: 1.0
    objective: binary:logistic

data:
  id_col: b_cpr
  label_col: ptb
  label_func: 
    func: get_binary_label
    args:
      col: GA_days
      operator: "<"
      value: 259
      new_col: ptb
  drop_feature_cols:
    - m_cpr
    - pregnancy_start
    - pregnancy_end
    - GA_140_date
    - GA_days
    - GA_weeks
    - current_c_section
    - current_induced_labor
    - current_ptb
